---
# tasks file for firewall
- name: Install firewalld
  dnf: 
   name: firewalld
   state: present

- name: Start and enable firewalld
  service: 
   name: firewalld
   state: started
   enabled: yes

- name: Allow HTTP 
  ansible.posix.firewalld:
   service: http
   permanent: yes
   state: enabled
   immediate: yes
  
